-- 2.1. Disasters: The top-level event (e.g., "Gujarat Cyclone 2025")
CREATE TABLE disasters (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    name VARCHAR(255) NOT NULL,
    disaster_type VARCHAR(100), -- e.g., 'Flood', 'Earthquake', 'Fire'
    status VARCHAR(50) DEFAULT 'active', -- 'active', 'contained', 'resolved'
    -- The overall geographical area affected by the disaster
    affected_area GEOMETRY(Polygon, 4326),
    start_time TIMESTAMPTZ DEFAULT NOW(),
    end_time TIMESTAMPTZ
);

-- 2.2. Incidents: A specific event that needs a response (e.g., an SOS press)
CREATE TABLE incidents (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    -- An incident can be part of a larger disaster, or standalone
    disaster_id UUID REFERENCES disasters(id) ON DELETE SET NULL,
    reported_by_user_id UUID REFERENCES users(id) ON DELETE SET NULL,
    
    -- The exact location of the incident report
    location GEOMETRY(Point, 4326) NOT NULL,
    
    status VARCHAR(50) DEFAULT 'pending', -- 'pending', 'triaged', 'dispatch_assigned', 'on_scene', 'resolved', 'false_alarm'
    
    -- This is set by the AI Triage (FR 7.3) or a Coordinator
    severity_level VARCHAR(20) DEFAULT 'unknown', -- 'unknown', 'low' (Green), 'medium' (Yellow), 'high' (Red)
    
    -- A summary of the incident, can be auto-generated by AI
    title VARCHAR(255),
    
    reported_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2.3. Incident Reports: The *content* of a report from a civilian (FR 2.2)
CREATE TABLE incident_reports (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    incident_id UUID NOT NULL REFERENCES incidents(id) ON DELETE CASCADE,
    reporting_user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    report_type VARCHAR(50), -- 'sos_button', 'text_report', 'voice_report', 'media_upload'
    text_description TEXT,
    timestamp TIMESTAMPTZ DEFAULT NOW()
);

-- 2.4. Media Attachments: Stores paths to S3/MinIO for photos, videos, audio (FR 2.2)
CREATE TABLE media_attachments (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    report_id UUID REFERENCES incident_reports(id) ON DELETE SET NULL,
    -- We can also link media directly to other entities, e.g., a responder's field update
    -- incident_id UUID REFERENCES incidents(id), 
    
    uploader_user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    file_type VARCHAR(20) NOT NULL, -- 'image', 'video', 'audio'
    mime_type VARCHAR(100),
    
    -- Path to the file in object storage (e.g., S3)
    storage_path VARCHAR(1024) NOT NULL, 
    
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2.5. Voice Transcriptions: Stores ASR output (FR 7.2)
CREATE TABLE voice_transcriptions (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    -- Linked to the original audio file
    media_attachment_id UUID UNIQUE NOT NULL REFERENCES media_attachments(id) ON DELETE CASCADE,
    -- Can also be linked to a WebRTC call log
    -- webrtc_call_log_id UUID UNIQUE REFERENCES webrtc_call_logs(id),
    
    transcribed_text TEXT,
    confidence_score REAL,
    language_code VARCHAR(10), -- e.g., 'en-US', 'gu-IN'
    processed_at TIMESTAMPTZ DEFAULT NOW(),
    
    -- This text can be indexed for full-text search to find keywords
    -- (e.g., 'trapped', 'fire', 'bleeding') for AI triage
    search_vector TSVECTOR
);

-- 2.6. AI Triage Logs: Logs *why* a severity was assigned (FR 7.3)
CREATE TABLE incident_triage_logs (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    incident_id UUID NOT NULL REFERENCES incidents(id) ON DELETE CASCADE,
    triage_source VARCHAR(50), -- 'ai_model', 'manual_coordinator'
    severity_assessment VARCHAR(20) NOT NULL, -- 'low', 'medium', 'high'
    reasoning TEXT, -- e.g., "Keywords 'trapped', 'bleeding' detected in ASR"
    confidence_score REAL,
    timestamp TIMESTAMPTZ DEFAULT NOW()
);