/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProtectedResourcesRouteImport } from './routes/_protected/resources'

const ProtectedResourcesRoute = ProtectedResourcesRouteImport.update({
  id: '/_protected/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/resources': typeof ProtectedResourcesRoute
}
export interface FileRoutesByTo {
  '/resources': typeof ProtectedResourcesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_protected/resources': typeof ProtectedResourcesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/resources'
  fileRoutesByTo: FileRoutesByTo
  to: '/resources'
  id: '__root__' | '/_protected/resources'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ProtectedResourcesRoute: typeof ProtectedResourcesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_protected/resources': {
      id: '/_protected/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ProtectedResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  ProtectedResourcesRoute: ProtectedResourcesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
